language: python
python:
  - "3.8.5"
  - "3.8.4"
services: postgresql
env:
  - DJANGO=3.1 DB=postgresql
install:
  - pip install -r requirements.txt
before_script:
  - psql -c 'create database recipe_api_test;' -U postgres
script:
  - python /manage.py test && flake8
