language: python
python:
  - "3.8.5"
  - "3.8.4"
services: postgresql
env:
  - DJANGO=3.1 DB=postgresql
install:
  - pip install -r requirements.txt
before_script:
  - postgresql -e 'create database test;' -u root
script:
  - python manage.py test && flake8
